name: Mechstack
title: Mechstack
description: >- # this means to ignore newlines until the next yaml key
  Landing page for Mechstack, an LLC in Oklahoma created by Michael Smith.
color: "#062C06"
background_color: "#000000"
logo: "assets/icons/favicon.png"
apple_mask_icon: "assets/icons/apple-mask-icon.svg"
sharing_image: "assets/mechstack/headshot.png"
twitter: ""
